export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SINGLE_PRODUCT = "SINGLE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

export const CREATE_USER = "CREATE_USER";